license files
Signed-off-by: Kim Tsao <ktsao@redhat.com>

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -34,7 +34,19 @@ jobs:
     steps:
     - name: Check out code
       uses: actions/checkout@v2
-      
+
+    - name: Check license
+      run: |
+        go get github.com/google/addlicense@latest
+        git reset HEAD --hard
+        ./check_licences.sh          
+        if [[ $? != 0 ]]
+        then
+          echo "license headers not found:"
+          git --no-pager diff
+          exit 1
+        fi     
+
     - name: Check if index server build is working
       run: cd index/server && ./build.sh
 
